/**
 * Clause library — the jurisdiction-specific legal prose.
 *
 * Clauses are written in Markdown with template placeholders that resolve
 * against the EmploymentRecord. They live per-country in ./clauses/<iso>.ts.
 *
 * Critical design choice: clause TEXT is treated as data, not generated by
 * Claude from scratch. Claude composes documents by ASSEMBLING clauses and
 * filling placeholders — it does not invent legal wording. This is the
 * difference between a defensible draft and a hallucination.
 *
 * Where Claude DOES generate prose:
 *   - Plain-English summaries of routing decisions ("here's why I selected
 *     these clauses").
 *   - Gap-bridging proposals when a clause is missing for an exact combo.
 *   - Filling free-text slots within a clause (e.g. duties description).
 */
import type { DocumentType, ISOCountry } from './employment-record';

/* ── clause definition ────────────────────────────────────────────────── */

export type ClauseTopic =
  | 'parties'
  | 'validity'                                // start date, term type
  | 'trial_period'
  | 'duties'
  | 'place_of_work'
  | 'working_hours'
  | 'sunday_work'
  | 'compensation'
  | 'annual_leave'
  | 'notice_period'
  | 'collective_agreement'
  | 'confidentiality'
  | 'non_compete'
  | 'data_protection'
  | 'governing_law'
  | 'signature'
  | 'termination_reason'
  | 'final_pay'
  | 'severance'
  | 'rehire'
  | 'addendum_recital'
  | 'addendum_delta'
  | 'visa_support';

export type RegulationCitation = {
  statute: string;                            // e.g. "Employment Contracts Act"
  section?: string;                           // e.g. "Chapter 6 §1"
  url?: string;
  /** Verbatim text if quoting is required. Mark `null` to defer to retrieval. */
  quotedText?: string | null;
};

export type Clause = {
  clauseId: string;                           // e.g. "fin.cba_binding"
  jurisdiction: ISOCountry;
  topic: ClauseTopic;
  applicableTo: DocumentType[];

  /**
   * Markdown body with `{{record.path}}` placeholders. Conditional blocks
   * use `{{#if record.path}}...{{/if}}`. Resolved by the composer.
   *
   * IMPORTANT: This text is the LEGAL CONTENT. It must be authored or
   * approved by counsel. Lumina renders it; it does not generate it.
   */
  body: string;

  /** Citations the clause depends on — surfaced in the document's references. */
  citations: RegulationCitation[];

  /**
   * Marks the clause as authoritatively sourced. PoC default is 'unverified';
   * counsel review flips to 'verified'.
   */
  reviewStatus: 'unverified' | 'pending_review' | 'verified';

  /** Optional: signals the composer to ask Claude to fill a free-text slot. */
  freeTextSlots?: Array<{
    name: string;                             // e.g. "duties_description"
    /** Guidance Claude uses to write the slot. */
    instructions: string;
    /** Maximum characters. Keeps Claude from rambling. */
    maxChars?: number;
  }>;
};

/* ── library interface ────────────────────────────────────────────────── */

export interface ClauseLibrary {
  /** Fetch by id. Null if unknown. */
  get(clauseId: string): Clause | null;
  /** Find every clause for a jurisdiction × doc type. */
  list(jurisdiction: ISOCountry, docType: DocumentType): Clause[];
  /** Find by topic — useful for cross-country comparison. */
  byTopic(topic: ClauseTopic): Clause[];
}
